[technote]
id = "SQR-111"
series_id = "SQR"
canonical_url = "https://sqr-111.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-111"
github_default_branch = "main"
date_created = 2026-01-28
date_updated = 2026-01-28
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "allberyr"
orcid = "https://orcid.org/0009-0009-9491-8923"

name = {given = "Russ", family = "Allbery"}
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Tucson"
ror = "https://ror.org/048g3cy84"
[[technote.authors]]
name = {given = "Dan C.", family = "Fuchs"}
internal_id = "fuchsds"
orcid = "https://orcid.org/0009-0007-2454-1951"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
ror = "https://ror.org/05gzmn429"
